import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { Code, ArrowRight, CheckCircle } from 'lucide-react';

const LandingPage = () => {
  const { user } = useAuth();

  return (
    <div className="min-h-screen bg-gray-900">
      {/* Hero Section */}
      <div className="relative pt-6 pb-16 sm:pb-24">
        <nav className="relative max-w-7xl mx-auto flex items-center justify-between px-4 sm:px-6">
          <div className="flex items-center flex-1">
            <div className="flex items-center justify-between w-full md:w-auto">
              <a href="#" className="flex items-center">
                <Code className="h-8 w-8 text-indigo-500" />
                <span className="ml-2 text-xl font-bold text-white">CodeArena</span>
              </a>
            </div>
          </div>
          <div className="hidden md:flex md:items-center md:space-x-6">
            {user ? (
              <Link to="/dashboard" className="btn-primary">
                Go to Dashboard
              </Link>
            ) : (
              <>
                <Link to="/login" className="text-base font-medium text-white hover:text-gray-300">
                  Log in
                </Link>
                <Link to="/register" className="btn-primary">
                  Register
                </Link>
              </>
            )}
          </div>
        </nav>

        <main className="mt-16 mx-auto max-w-7xl px-4 sm:mt-24 sm:px-6">
          <div className="text-center">
            <h1 className="text-4xl tracking-tight font-extrabold text-white sm:text-5xl md:text-6xl">
              <span className="block">Master Competitive Coding</span>
              <span className="block text-indigo-500">with AI-Powered Practice</span>
            </h1>
            <p className="mt-3 max-w-md mx-auto text-base text-gray-300 sm:text-lg md:mt-5 md:text-xl md:max-w-3xl">
              Enhance your coding skills with personalized AI mock tests and compete with peers in real-time coding challenges.
            </p>
            <div className="mt-5 max-w-md mx-auto sm:flex sm:justify-center md:mt-8">
              {user ? (
                <Link to="/dashboard" className="btn-primary flex items-center justify-center px-8 py-3 text-lg">
                  Go to Dashboard
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              ) : (
                <>
                  <div className="rounded-md shadow">
                    <Link to="/register" className="btn-primary flex items-center justify-center px-8 py-3 text-lg">
                      Get Started
                      <ArrowRight className="ml-2 h-5 w-5" />
                    </Link>
                  </div>
                  <div className="mt-3 sm:mt-0 sm:ml-3">
                    <Link to="/login" className="btn-secondary flex items-center justify-center px-8 py-3 text-lg">
                      Log In
                    </Link>
                  </div>
                </>
              )}
            </div>
          </div>
        </main>
      </div>

      {/* Features */}
      <div className="py-12 bg-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="lg:text-center">
            <h2 className="text-base text-indigo-400 font-semibold tracking-wide uppercase">Features</h2>
            <p className="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-white sm:text-4xl">
              Everything you need to excel
            </p>
            <p className="mt-4 max-w-2xl text-xl text-gray-300 lg:mx-auto">
              Our platform offers comprehensive tools to help you improve your coding skills and prepare for competitive programming contests.
            </p>
          </div>

          <div className="mt-10">
            <div className="space-y-10 md:space-y-0 md:grid md:grid-cols-2 md:gap-x-8 md:gap-y-10">
              {[
                {
                  name: 'AI-Powered Mock Tests',
                  description: 'Practice with personalized coding challenges generated by AI based on your skill level and preferred topics.'
                },
                {
                  name: 'Real-time Competitions',
                  description: 'Create or join coding rooms to compete with friends and peers in real-time coding challenges.'
                },
                {
                  name: 'Code Analysis',
                  description: 'Get instant feedback on your code quality, time complexity, and performance metrics.'
                },
                {
                  name: 'Progress Tracking',
                  description: 'Monitor your improvement over time with detailed statistics and performance history.'
                }
              ].map((feature, index) => (
                <div key={index} className="relative">
                  <div className="absolute flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
                    <CheckCircle className="h-6 w-6" />
                  </div>
                  <div className="ml-16">
                    <h3 className="text-lg leading-6 font-medium text-white">{feature.name}</h3>
                    <p className="mt-2 text-base text-gray-300">{feature.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Mobile CTA */}
      <div className="md:hidden fixed bottom-0 inset-x-0 pb-2 bg-gray-900 backdrop-blur-sm bg-opacity-80">
        <div className="flex items-center justify-around">
          {user ? (
            <Link to="/dashboard" className="btn-primary w-full mx-4 py-3 text-center">
              Go to Dashboard
            </Link>
          ) : (
            <>
              <Link to="/login" className="btn-secondary flex-1 mx-2 py-3 text-center">
                Log In
              </Link>
              <Link to="/register" className="btn-primary flex-1 mx-2 py-3 text-center">
                Register
              </Link>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default LandingPage;